apiVersion: agh.lkc-lab.com/v3alpha1
kind: UpgradePlan
spec:
  system:
    appVersion: "v3.9.2"
    chartVersion: "v3.10.13"
    patches:
      - op: replace
        path: /spec/version
        value: "3.10.13"
    releaseLog: ""
  package:
    version: v1.8.5
    updaterTag: v1.11.0-agh3-v1.8.5-all
    releaseLog: ""
  agentServer:
    version: v2.4.1
    releaseLog: "Add select and forget agent"
