apiVersion: agh.lkc-lab.com/v3alpha1
kind: UpgradePlan
spec:
  system:
    appVersion: "v3.4.4"
    chartVersion: "3.6.5"
    patches:
      - op: replace
        path: /spec/version
        value: "3.6.5"
    releaseLog: |-
      - Custom Variable
  package:
    version: v1.3.1
    updaterTag: v1.10.3-agh3-v1.3.1-all
    releaseLog: ""
