apiVersion: agh.lkc-lab.com/v3alpha1
kind: UpgradePlan
spec:
  system:
    appVersion: "v3.11.2"
    chartVersion: "3.12.8"
    patches:
      - op: replace
        path: /spec/version
        value: "3.12.8"
    releaseLog: ""
    requiredPackageVersion: "v1.10.1"
  package:
    version: v1.10.1
    updaterTag: v1.11.0-agh3-v1.10.1-all
    releaseLog: ""
    requiredAppVersion: "v3.10"
  agentServer:
    version: v2.8.0
    releaseLog: ""
