apiVersion: agh.lkc-lab.com/v3alpha1
kind: UpgradePlan
spec:
  system:
    appVersion: "v3.4.2"
    chartVersion: "3.6.3"
    patches:
      - op: replace
        path: /spec/version
        value: "3.6.3"
    releaseLog: |-
      New Features:
      - Custom Variable
      - Playbook search enhancement
      - Rename CEIAE to ATTACK Surfaces
      - Rename Resource to Playbook
      - System performance optimization

      Bug Fixes:
      - Filter operation system by platform
  package:
    version: v1.3.1
    updaterTag: v1.10.3-agh3-v1.3.1-all
    releaseLog: ""
