apiVersion: agh.lkc-lab.com/v3alpha1
kind: UpgradePlan
spec:
  system:
    appVersion: "v3.11.3"
    chartVersion: "3.12.15"
    patches:
      - op: replace
        path: /spec/version
        value: "3.12.15"
    releaseLog: ""
    requiredPackageVersion: "v1.10.2"
  package:
    version: v1.11.3
    updaterTag: v1.15.0-agh3-v1.11.3-all
    releaseLog: ""
    requiredAppVersion: "v3.10"
  agentServer:
    version: v2.8.0
    releaseLog: ""
