apiVersion: agh.lkc-lab.com/v3alpha1
kind: UpgradePlan
spec:
  system:
    appVersion: "v3.8.8"
    chartVersion: "3.10.8"
    patches:
      - op: replace
        path: /spec/version
        value: "3.10.8"
    releaseLog: ""
  package:
    version: v1.8.6
    updaterTag: v1.11.0-agh3-v1.8.6-all
    releaseLog: "Playbook error corrections and quality improvement."
  agentServer:
    version: v2.4.1
    releaseLog: "Add select and forget agent"
