apiVersion: agh.lkc-lab.com/v3alpha1
kind: UpgradePlan
spec:
  system:
    appVersion: "v3.4.1"
    chartVersion: "3.6.2"
    patches:
      - op: replace
        path: /spec/version
        value: "3.6.2"
    releaseLog: |-
      New Features:
      - Execution result enhancement
      - Playbook selection enhancement
      - System OTA support
      - I18n support enhancement
      - System performance optimization
      - System Agent/C2 service stability optimization

      Bug Fixes:
      - Fix the problem of the MQ service failure caused by the abnormal exit of the execution
      - Auto recovery of the abnormal status of MQ channel/connection
  package:
    version: v1.1.0
    updaterTag: v1.10.3-agh3-v1.1.0-all
    releaseLog: ""
